name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push sriov-network-device-plugin
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/ppc64le
        push: false
        file: images/Dockerfile.ppc64le
